---
- name: Prints the facts and save them on a facts.txt
  hosts: host-ubuntu
  tasks:
    - name: Print OS family to file
      shell: echo "The Linux OS family is {{ansible_os_family}}." > /home/{{ansible_user_id}}/os-family.txt
    - name: Print default machine NIC name to console
      debug: msg="{{ansible_default_ipv4.interface}}"
    - name: Register ls results variable
      command: "ls"
      register: dirs
    - name: Print 'dirs' variable from last step to console
      debug:
        msg: "{{dirs}}"